---
markdown: redcarpet

# Change these to match your domain setup
baseurl: "/jekyll-assets/"
url: "http://localhost"

#
# Jekyll-Assets configuration
#

assets:
  compress:
    css: sass
    js:  uglifier
